---
title: "Covid Data Between State With The Highest Vaccine Rate and State With The Lowest Vaccine Rate"
author: "B. Han"
date: "2025-02-17"
output:
  pdf_document: default
  html_document: default
---
```
I will be comparing the Covid deaths per thousand vs Cases per thousand between 
the state with the highest vaccine rate Rhode Island and the state with the 
lowest vaccine rate Wyoming. The hope is to find a similar correlation in the 
beginning and some alterations between the two states as the the vaccine is 
rolled out later on in the data. For most of the clean up I followed the videos 
in the course, but decided to focus my analysis on Wyoming and Rhode Island
```

```{r setup, results = "hide"}
knitr::opts_chunk$set(echo = TRUE)
library(stringr)
library(readr)
library(dplyr)
library(tidyr)
library(lubridate)
library(ggplot2)
```

## R Markdown
## Importing and Transforming
```{r, results = "hide"}
url_in <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/"

file_names <-
c("time_series_covid19_confirmed_US.csv",  "time_series_covid19_confirmed_global.csv", "time_series_covid19_deaths_US.csv",  "time_series_covid19_deaths_global.csv")

urls <- str_c(url_in, file_names)

global_cases <- read_csv(urls[2])
global_deaths <- read_csv(urls[4])
US_cases <- read_csv(urls[1])
US_deaths <- read_csv(urls[3])
```
## Cleaning and joining cases and deaths
```{r, results = "hide"}
global_cases <- global_cases %>%
  pivot_longer(cols =
-c('Province/State',
'Country/Region', Lat, Long),
                    names_to = "date",
                  values_to = "cases") %>%
  select(-c(Lat,Long))
  
global_deaths <- global_deaths %>%
  pivot_longer(cols = -c('Province/State',
                          'Country/Region', Lat, Long),
                names_to = "date",
                values_to = "deaths") %>%
  select(-c(Lat, Long))
  

global <- global_cases %>%
      full_join(global_deaths) %>%
      rename(Country_Region = 'Country/Region',
            Province_State = 'Province/State') %>%
      mutate(date = mdy(date))
      
      
global <- global %>% filter(cases > 0)

global %>% filter(cases > 28000000)


US_cases <- US_cases %>%
  pivot_longer(cols = -(UID:Combined_Key),
                names_to = "date",
                values_to = "cases") %>%
  select(Admin2:cases) %>%
  mutate(date = mdy(date)) %>%
  select(-c(Lat,Long_))
  
  
  
US_deaths <- US_deaths %>%
  pivot_longer(cols = -(UID:Population),
                names_to = "date",
                values_to = "deaths") %>%
  select(Admin2:deaths) %>%
  mutate(date = mdy(date)) %>%
  select(-c(Lat,Long_))
  
US <- US_cases %>%
      full_join(US_deaths)

global <- global %>%
    unite("Combined_Key",
    c(Province_State, Country_Region),
    sep = ", ",
    na.rm = TRUE,
    remove = FALSE)

uid_lookup_url <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv"

uid <- read_csv(uid_lookup_url) %>%
  select(-c(Lat, Long_, Combined_Key, code3, iso2, iso3, Admin2))


global <- global %>%
    left_join(uid, by = c("Province_State", "Country_Region")) %>%
    select(-c(UID, FIPS)) %>%
    select(Province_State, Country_Region, date, cases, deaths, Population, Combined_Key)
```
## US data by State
```{r}

US_by_state <- US %>%
    group_by(Province_State, Country_Region, date) %>%
    summarize(cases = sum(cases), deaths = sum(deaths),
              Population = sum(Population)) %>%
    mutate(deaths_per_mill = deaths * 1000000 / Population) %>%
    select(Province_State, Country_Region, date, cases, 
            deaths, deaths_per_mill, Population) %>%
    ungroup()
    
    
    
US_totals <- US_by_state %>%
    group_by(Country_Region, date) %>%
    summarize(cases = sum(cases), deaths = sum(deaths),
              Population = sum(Population)) %>%
    mutate(deaths_per_mill = deaths * 1000000 / Population) %>%
    select(Country_Region, date, cases, 
            deaths, deaths_per_mill, Population) %>%
    ungroup()
```

## US Totals Plot
```{r}
US_totals %>% 
    filter(cases > 0) %>%
    ggplot(aes(x = date, y = cases)) +
    geom_line(aes(color = "cases")) + 
    geom_point(aes(color = "cases")) + 
    geom_line(aes(y = deaths, color = "deaths")) + 
    geom_point(aes(y = deaths, color = "deaths")) + 
    scale_y_log10() +
    theme(legend.position = "bottom",
          axis.text.x = element_text(angle = 90)) + 
    labs(title = "COVID19 in US", y = NULL)
```

## Rhode Island and Wyoming State Level Analysis
```{r}
state <- "Rhode Island"
US_by_state %>% 
  filter(Province_State == state) %>%
  filter(cases > 0) %>%
  ggplot(aes(x = date)) + 
    geom_line(aes(y = cases, color = "Cases")) + 
    geom_point(aes(y = cases, color = "Cases")) + 
    geom_line(aes(y = deaths, color = "Deaths")) + 
    geom_point(aes(y = deaths, color = "Deaths")) + 
    scale_y_log10() +
    theme(legend.position = "bottom",
          axis.text.x = element_text(angle = 90)) + 
    labs(title = str_c("COVID-19 in ", state), y = NULL, color = "Legend")
    
state <- "Wyoming"
US_by_state %>% 
  filter(Province_State == state) %>%
  filter(cases > 0) %>%
  ggplot(aes(x = date)) + 
    geom_line(aes(y = cases, color = "Cases")) + 
    geom_point(aes(y = cases, color = "Cases")) + 
    geom_line(aes(y = deaths, color = "Deaths")) + 
    geom_point(aes(y = deaths, color = "Deaths")) + 
    scale_y_log10() +
    theme(legend.position = "bottom",
          axis.text.x = element_text(angle = 90)) + 
    labs(title = str_c("COVID-19 in ", state), y = NULL, color = "Legend")
    
max(US_totals$date)
```
## Chose the highest vaccine rate state and lowest rate state
```{r}
highest_lowest_vaccine_states <- c("Wyoming", "Rhode Island")

States_selected <- US_by_state %>%
  filter(Province_State %in% highest_lowest_vaccine_states)
  
States_selected <- States_selected %>%
  mutate(cases_per_thou = 1000 * cases / Population,
  deaths_per_thou = 1000 * deaths / Population)
```  
## Rhode Island Linear Model
```{r}
RI_Model <- lm(deaths_per_thou ~ cases_per_thou, data = filter(States_selected, Province_State == "Rhode Island"))
summary(RI_Model)
```
## Wyoming Linear Model
```{r}
WY_Model <- lm(deaths_per_thou ~ cases_per_thou, data = filter(States_selected, Province_State == "Wyoming"))
summary(WY_Model)
```
## Combine the Rhode Island and Wyoming plots with the LM model 
```{r}
States_selected %>%
  ggplot(aes(x = cases_per_thou, y= deaths_per_thou, color = Province_State)) +
  geom_point() + 
  geom_smooth(method = "lm", aes(color = Province_State)) +
  labs(title = "Deaths per Thou vs Cases per Thou in Rhode Island and Wyoming",
  x = "Cases per Thou",
  y = "Deaths per Thou") + theme_minimal()
```
```
We can see that although Rhode Island starts with a very sharp slope, the slope 
tends to taper off, while in Wyoming the slope of is steep and remains steep to 
the point where the deaths per thousand crosses Rhode Island's at some point. 
We see two very long tapering off sections of deaths for Rhode Island, which 
probably correlates to the vaccine roll out, and while we see two smaller 
tapering sections in Wyoming the deaths per thousand continued to rise sharply. 
My conclusion would be that the Covid vaccine did provide a significant decrease
in mortality rate in patients and did in fact help prevent deaths. 

Some bias that have risen during this analysis is that Rhode island is about 
1 million in population size and Wyoming is about half of that in population 
and this could skew results as there is 2 times the amount of people in Rhode 
Island. Another bias is that Wyoming is a very big state than Rhode Island, 
making proximity to other residents much bigger than Rhode Island. Also, 
Rhode Island's proximity to New York which was one of the origin sites for 
Covid is much closer than to Wyoming, making it likely that Covid had infected 
Rhode Island much earlier than Wyoming. 
```
